// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPx4G2lsh9CZUyLrcb_MvnnXImsxyTb1Y',
    appId: '1:547444130498:web:6b8851b02ba5dfeb67b15b',
    messagingSenderId: '547444130498',
    projectId: 'ecoventure-app',
    authDomain: 'ecoventure-app.firebaseapp.com',
    storageBucket: 'ecoventure-app.firebasestorage.app',
    measurementId: 'G-9C4EY7QH7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoobGFb4xRqYiZIW8Pypot__ngbbQjoIM',
    appId: '1:547444130498:android:4d63070bf1544bbc67b15b',
    messagingSenderId: '547444130498',
    projectId: 'ecoventure-app',
    storageBucket: 'ecoventure-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4NxkLg0YqeWaxF_g8CCIIQDxPULBxD5s',
    appId: '1:547444130498:ios:18a621d0c0522ff167b15b',
    messagingSenderId: '547444130498',
    projectId: 'ecoventure-app',
    storageBucket: 'ecoventure-app.firebasestorage.app',
    androidClientId: '547444130498-n6rbkid5620dsipjc9ub62c0rbralkjv.apps.googleusercontent.com',
    iosClientId: '547444130498-cknoptbir1m43juu6qbn5rt6nbi2572p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoVentureAdminPortal',
  );
}
